### PR TITLE
[utils] Fix leaks and general improvements

### PR DESCRIPTION
**Pull request by Iscle**
I fixed a few resource leaks that could happen. I also moved xz and commons-compress to be handled by Gradle.

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
can you rake a look at this 

* What went wrong:
Execution failed for task ':utils:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :utils project caused this error: /home/runner/work/MCinaBox/MCinaBox/utils/libs/fileSelector.aar

**Comment by LegacyGamerHD** [comment]
it happens when i setup the devbuild system

**Comment by Iscle** [comment]
> can you rake a look at this

I've never worked with .aar files. However I also don't understand why we're using them in this case. Nor I understand why there are prebuilt libraries if all of them are open-source. If it was my project, I'd remove the .aar files, add the source code to be built every time, and also fix the project structure.

May I know what CI are you trying to configure?

**Comment by LegacyGamerHD** [comment]
github ci also its in source code i didnt put it there

**Comment by LegacyGamerHD** [comment]
it works fine on my pc do with android studio https://github.com/AOF-Dev/MCinaBox/blob/dev/utils/libs/fileSelector.aar

**Pull request merged**
