### PR TITLE
Dev builds

### PR DESCRIPTION
**Pull request by LegacyGamerHD**
the dev builds are fully working rn yaay but idk how to do the multi arch

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
@Iscle @longjunyu2 its working yaay when merge

**Comment by LegacyGamerHD** [comment]
do not merge yet it hase only 64 bit

**Comment by LegacyGamerHD** [comment]
ready for merge guys

**Comment by LegacyGamerHD** [comment]
credit goes to pojav first tbh as its mostly is there dev build system

**Comment by AyHa1810** [comment]
Bro why am I excited for this PR to get merged? Lol XD
BTW, the code seems good and working. I hope it gets merged.

**Comment by Iscle** [comment]
I'll test it once I get home and merge it :)

**Comment by AyHa1810** [comment]
@Iscle well, I checked it, and it's actually working! The proof is [here](https://github.com/LoyaltyMC/MCinaBox/actions)!

**Comment by AyHa1810** [comment]
@LegacyGamerHD it need some minor fixes. Change the values `32-bit` and `64-bit` to `aarch32` and `aarch64` in `android.yml` to make it correctly understandable.

**Comment by LegacyGamerHD** [comment]
> @LegacyGamerHD it need some minor fixes. Change the values `32-bit` and `64-bit` to `aarch32` and `aarch64` in `android.yml` to make it correctly understandable.

done 👍

**Comment by AyHa1810** [comment]
Now, the code is totally fine and working. @Iscle or @longjunyu2, merge it.

**Comment by Iscle** [comment]
I made a few changes to the file and pushed it myself. I gave credits to you in the commit description. For some reason I could not edit your PR.

**Comment by LegacyGamerHD** [comment]
@Iscle it uses only aarch64 now

**Comment by Iscle** [comment]
No, it's muli-arch by default. If you open the generated .apk with a Zip archive manager, you'll see that native libraries for both architectures are built.

**Comment by LegacyGamerHD** [comment]
> No, it's muli-arch by default. If you open the generated .apk with a Zip archive manager, you'll see that native libraries for both architectures are built.

its not

**Comment by LegacyGamerHD** [comment]
i tryde installing even latest release is sepreted

**Comment by Iscle** [comment]
No, the latest release is one package, like it has always been: https://github.com/AOF-Dev/MCinaBox/releases/tag/v0.1.3

I'll try now on a 32-bit device, but I'm sure I'm right here.

**Comment by LegacyGamerHD** [comment]
@Iscle  hey i dont agree also @longjunyu2 on prerelease

**Comment by LegacyGamerHD** [comment]
PLEASE import correct runtime for your mcinabox. ( aarch32 ->mcinabox-arm32 , aarch64 -> mcinabox-arm64 )
If you want to start 1.15+, download the runtime for arm32 without updating it
's version.After entering the game, turn off the original input in the mouse options of the control settings, and reset your keys in the control settings.

**Comment by LegacyGamerHD** [comment]
> No, the latest release is one package, like it has always been: https://github.com/AOF-Dev/MCinaBox/releases/tag/v0.1.3
> 
> I'll try now on a 32-bit device, but I'm sure I'm right here.

wrong again

**Comment by LegacyGamerHD** [comment]
@Iscle  also i removed the aar file

**Comment by LegacyGamerHD** [comment]
i added the depencie etc removed the aar and you just keep the aar file rigth give good reason why to modify my commit @Iscle

**Comment by LegacyGamerHD** [comment]
whats not good about my pull

**Comment by Iscle** [comment]
Well, I was not modifying your commit to keep the .aar file. I was modifying it because your file was not completely perfect. We only need to build 1 apk file, that will work for both runtime packages (aarch32 and aarch64).

I just tested it on an aarch32 and aarch64 device and it works perfectly. What you're complaining about is the runtime package, it has nothing to do with the .apk file.

My modification to the file just improves it, that's it. I gave you proper credits, what more do you want?

**Comment by LegacyGamerHD** [comment]
> Well, I was not modifying your commit to keep the .aar file. I was modifying it because your file was not completely perfect. We only need to build 1 apk file, that will work for both runtime packages (aarch32 and aarch64).
> 
> I just tested it on an aarch32 and aarch64 device and it works perfectly. What you're complaining about is the runtime package, it has nothing to do with the .apk file.
> 
> My modification to the file just improves it, that's it. I gave you proper credits, what more do you want?

i removed it

**Comment by LegacyGamerHD** [comment]
fucking hell

**Comment by LegacyGamerHD** [comment]
look trought it

**Comment by LegacyGamerHD** [comment]
> Well, I was not modifying your commit to keep the .aar file. I was modifying it because your config was not completely perfect. We only need to build 1 apk file, that will work for both runtime packages (aarch32 and aarch64).
> 
> I just tested it on an aarch32 and aarch64 device and it works perfectly. What you're complaining about is the runtime package, it has nothing to do with the .apk file.
> 
> My modification to the file just improves it, that's it. I gave you proper credits, what more do you want?

sure you know that release does that to i dont think you understand github

**Comment by LegacyGamerHD** [comment]
look here

**Comment by LegacyGamerHD** [comment]
https://github.com/AOF-Dev/MCinaBox/releases/tag/v0.1.4-p4

**Comment by LegacyGamerHD** [comment]
> Well, I was not modifying your commit to keep the .aar file. I was modifying it because your config was not completely perfect. We only need to build 1 apk file, that will work for both runtime packages (aarch32 and aarch64).
> 
> I just tested it on an aarch32 and aarch64 device and it works perfectly. What you're complaining about is the runtime package, it has nothing to do with the .apk file.
> 
> My modification to the file just improves it, that's it. I gave you proper credits, what more do you want?

also tell me whats wrong if its not perfect....

**Comment by Iscle** [comment]
I think you're the one not understanding what we're dealing with here.

The GitHub Actions you posted (which I corrected) is only building the .apk file. The .apk file is automatically built for both architectures. That's all we're doing here.

What you are complaining about right now is the runtime package. The runtime package is not being build neither by your proposed workflow nor mine. Those are built by @longjunyu2 privately and uploaded from time to time, when a modification is done.

> also tell me whats wrong if its not perfect....
You were using some deprecated environment variables, and building an APK with aarch32+aarch64 support, and then another one with just aarch32 support (this makes no sense).

Please don't commit changes to working code if it's not for an improvement. Try to understand my commit first, and then let's discuss if you find something wrong with it.

If you want to build the runtime libraries too, we can do it. It's just that it's not possible right now with the source code we have in this repository.

**Comment by Iscle** [comment]
> https://github.com/AOF-Dev/MCinaBox/releases/tag/v0.1.4-p4

This is just not needed. Android allows multi-arch apk files.

**Comment by LegacyGamerHD** [comment]
> > https://github.com/AOF-Dev/MCinaBox/releases/tag/v0.1.4-p4
> 
> This is just not needed. Android allows multi-arch apk files.

talk with @longjunyu2  then

**Comment by Iscle** [comment]
> > > https://github.com/AOF-Dev/MCinaBox/releases/tag/v0.1.4-p4
> > 
> > 
> > This is just not needed. Android allows multi-arch apk files.
> 
> talk with @longjunyu2 then

I'll do, once he's not busy anymore.

BTW, here's proof: https://prnt.sc/v1ts80

**Comment by LegacyGamerHD** [comment]
> I think you're the one not understanding what we're dealing with here.
> 
> The GitHub Actions you posted (which I corrected) is only building the .apk file. The .apk file is automatically built for both architectures. That's all we're doing here.
> 
> What you are complaining about right now is the runtime package. The runtime package is not being build neither by your proposed workflow nor mine. Those are built by @longjunyu2 privately and uploaded from time to time, when a modification is done.
> 
> > also tell me whats wrong if its not perfect....
> 
> You were using some deprecated environment variables, and building an APK with aarch32+aarch64 support, and then another one with just aarch32 support (this makes no sense).
> 
> Please don't commit changes to working code if it's not for an improvement. Try to understand my commit first, and then let's discuss if you find something wrong with it.
> 
> If you want to build the runtime libraries too, we can do it. It's just that it's not possible right now with the source code we have in this repository.
am kinda fucking mad if revert again then i quit fun fact i removed the aar file and add depencie for it

**Comment by LegacyGamerHD** [comment]
if its about the android ci file fine by me but forgot 50%  of the other stuff like adding the depancie its the same as aar file

**Comment by Iscle** [comment]
Hey, no need to be rude.

Yes, I know you removed the dependency, that's great! I was looking into that too (actually, I have it done manually), but your PR was for the CI, not for the .aar files.

Also, try to do more descriptive commits please. We want a clean git history :)

**Comment by LegacyGamerHD** [comment]
> Hey, no need to be rude.
> 
> Yes, I know you removed the dependency, that's great! I was looking into that too (actually, I have it done locally), but your PR was for the CI, not for the .aar files.
> 
> Also, try to do more descriptive commits please. We want a clean git history :)

okay but it kept about ci from building

**Comment by LegacyGamerHD** [comment]
thats why i added it in

**Comment by Iscle** [comment]
Yeah, but my file version fixed the issue :)

**Comment by khanhduytran0** [comment]
> No, it's muli-arch by default. If you open the generated .apk with a Zip archive manager, you'll see that native libraries for both architectures are built.

But if install to arm64 device, it will find **from 64bit to 32bit** so it pick arm64 native libs and can't run 1.15+ due to namespace problem.

**Comment by Iscle** [comment]
That is possible. Could you elaborate a bit more on the issue, so that we can try to find a fix that does not involve dual apks?

Thanks!

**Comment by khanhduytran0** [comment]
It's in [your issue](https://github.com/AOF-Dev/MCinaBox/issues/532#issuecomment-708502315).

**Comment by Iscle** [comment]
> It's in [your issue](https://github.com/AOF-Dev/MCinaBox/issues/532#issuecomment-708502315).

Oh, yeah! But that was me trying aarch64, I haven't tried aarch32 in a 64 bit phone. Does the same issue arrise?

**Comment by khanhduytran0** [comment]
If you run aarch32 (and APK only contains armv7 libs) in aarch64, GLFW load then 1.15+ will work.

**Pull request merged**
