### PR TITLE
Only deleting a word for grammer

### PR DESCRIPTION
**Pull request by AyHa1810**
I just deleted a word for grammer lol

### CODE REVIEW

**Comment by longjunyu2** [comment]
@AyHa1810 Good work. But I think it is better to change the string-en.xml too.

**Comment by longjunyu2** [comment]
The string-en.xml should be the same as the main string.xml, I think.

**Comment by AyHa1810** [comment]
Ok

**Comment by longjunyu2** [comment]
Thanks!

**Pull request merged**
