### PR TITLE
[WIP] github ci devbuilds

### PR DESCRIPTION
**Pull request by LegacyGamerHD**
curently not working because a .aar file being in way i kinda need help about

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
thats tge current error i got rn i will be small break rn

**Comment by longjunyu2** [comment]
Very glad to see your work.
This will help the project a lot.

**Review by longjunyu2 — COMMENTED** [review]
I used to build jni files with ndk 21 and higher.
It passed, but I only get some strange errors when ran them.
This can cause problems with the dlopen function.
So I think it is better to use ndk 16 instead.

**Comment by LegacyGamerHD** [comment]
> I used to build jni files with ndk 21 and higher.
> It passed, but I only get some strange errors when ran them.
> This can cause problems with the dlopen function.
> So I think it is better to use ndk 16 instead.

done i set the ndk to 16.1.4479499 how it was

**Comment by longjunyu2** [comment]
Are you still meeting some problems?

**Comment by LegacyGamerHD** [comment]
> Are you still meeting some problems?

Yes I have still having issues

**Comment by Iscle** [comment]
Hi.

I know this is marked as a draft, but please, before doing the final pull request, make sure to clean up the git history so that we can keep track of the changes and have a clean history.

Thanks :)

**Comment by LegacyGamerHD** [comment]
> Hi.
> 
> I know this is marked as a draft, but please, before doing the final pull request, make sure to clean up the git history so that we can keep track of the changes and have a clean history.
> 
> Thanks :)

Yeah sure

**Pull request closed without merging**
